import React, { useState } from 'react';
import { AuroraCard, AuroraButton } from '../components/AuroraUI';
import { LIBRARY_DATA, UNITREE_REPORT, CATL_REPORT } from '../data/mockData';
import { 
  Lock, 
  FileText, 
  User, 
  Layers, 
  X, 
  ChevronRight,
  AlertCircle,
  CheckCircle2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// --- Reusable Report Content Component (Adapted for Modal) ---
const ReportContent = ({ data, company }: { data: any, company: string }) => {
  return (
    <div className="space-y-8 pb-20">
      <div className="mb-8">
        <h1 className="text-4xl font-display font-bold text-white mb-2">{company}</h1>
        <div className="flex items-center gap-4 text-sm text-aria-text-sub">
          <span className="px-2 py-1 bg-white/5 rounded border border-white/10">Full In-Depth Report</span>
          <span>Generated by ARIA v2.3</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>

      {/* M0 */}
      <section id="m0" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M0</span>
          <h3 className="text-xl font-display font-bold text-white">投资概览</h3>
        </div>
        <AuroraCard className="p-6 border-l-4 border-l-aria-cyan">
          <div className="flex justify-between items-start mb-4">
            <div className="text-aria-text-sub text-sm font-mono">RATING</div>
            <div className="text-2xl font-bold text-aria-cyan">{data.m0.rating}/5.0</div>
          </div>
          <p className="text-aria-text-main mb-4 leading-relaxed">{data.m0.conclusion}</p>
          <div className="flex items-start gap-2 text-sm text-aria-orange/80 bg-aria-orange/5 p-3 rounded">
            <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
            {data.m0.risks}
          </div>
        </AuroraCard>
      </section>

      {/* M1 */}
      <section id="m1" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M1</span>
          <h3 className="text-xl font-display font-bold text-white">市场测算</h3>
        </div>
        <div className="bg-[#0A1023] p-4 rounded-lg border border-white/10 font-mono text-sm text-aria-cyan mb-4 overflow-x-auto">
          {data.m1.formula}
        </div>
        <div className="grid grid-cols-3 gap-4">
          {data.m1.scenarios.map((s: any, i: number) => (
            <AuroraCard key={i} className="p-3 text-center">
              <div className="text-xs text-aria-text-sub mb-1">{s.name}</div>
              <div className="text-lg font-bold text-white mb-1">{s.value}</div>
              <div className="text-[10px] text-aria-text-sub/70">{s.assumption}</div>
            </AuroraCard>
          ))}
        </div>
      </section>

      {/* M2 */}
      <section id="m2" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M2</span>
          <h3 className="text-xl font-display font-bold text-white">竞争格局</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-aria-text-sub font-mono text-xs bg-white/5">
              <tr>
                <th className="p-3 rounded-l-lg">Company</th>
                <th className="p-3">Type</th>
                <th className="p-3">Price</th>
                <th className="p-3">Tech</th>
                <th className="p-3 rounded-r-lg">Share</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {data.m2.competitors.map((c: any, i: number) => (
                <tr key={i} className="hover:bg-white/5 transition-colors">
                  <td className={`p-3 font-medium ${i === 0 ? 'text-aria-cyan' : 'text-white'}`}>{c.name}</td>
                  <td className="p-3 text-aria-text-sub">{c.type}</td>
                  <td className="p-3 text-aria-text-sub">{c.price}</td>
                  <td className="p-3 text-aria-text-sub">{c.tech}</td>
                  <td className="p-3 font-mono text-white">{c.share}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* M3 */}
      <section id="m3" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M3</span>
          <h3 className="text-xl font-display font-bold text-white">多维评分</h3>
        </div>
        <div className="space-y-3">
          {data.m3.scores.map((s: any, i: number) => (
            <div key={i} className="flex items-center gap-4">
              <span className="w-20 text-sm text-aria-text-sub text-right">{s.label}</span>
              <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-aria-cyan to-aria-purple" 
                  style={{ width: `${(s.val / 5) * 100}%` }}
                />
              </div>
              <span className="w-8 font-mono text-sm text-white">{s.val}</span>
            </div>
          ))}
        </div>
      </section>

      {/* M5 */}
      <section id="m5" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M5</span>
          <h3 className="text-xl font-display font-bold text-white">政策追踪</h3>
        </div>
        <div className="space-y-3">
          {data.m5.policies.map((p: any, i: number) => (
            <AuroraCard key={i} className="p-4 flex items-start gap-4">
              <div className="text-xs font-mono text-aria-text-sub pt-1">{p.date}</div>
              <div className="flex-1">
                <div className="text-white font-medium mb-1">{p.name}</div>
                <div className={`text-xs inline-block px-2 py-0.5 rounded ${
                  p.impact === 'High' ? 'bg-aria-green/10 text-aria-green' :
                  p.impact === 'Med' ? 'bg-aria-cyan/10 text-aria-cyan' : 'bg-white/10 text-aria-text-sub'
                }`}>
                  Impact: {p.impact}
                </div>
              </div>
            </AuroraCard>
          ))}
        </div>
      </section>

      {/* M6 */}
      <section id="m6" className="scroll-mt-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="px-2 py-1 bg-aria-cyan/10 text-aria-cyan text-xs font-mono rounded">M6</span>
          <h3 className="text-xl font-display font-bold text-white">增长逻辑</h3>
        </div>
        <div className="space-y-3">
          {data.m6.positive.map((text: string, i: number) => (
            <div key={i} className="flex gap-3 p-3 bg-aria-cyan/5 border border-aria-cyan/10 rounded-lg">
              <CheckCircle2 className="w-5 h-5 text-aria-cyan flex-shrink-0" />
              <p className="text-sm text-aria-text-main">{text}</p>
            </div>
          ))}
          {data.m6.negative.map((text: string, i: number) => (
            <div key={i} className="flex gap-3 p-3 bg-aria-orange/5 border border-aria-orange/10 rounded-lg">
              <AlertCircle className="w-5 h-5 text-aria-orange flex-shrink-0" />
              <p className="text-sm text-aria-text-main">{text}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export const ReportLibrary = () => {
  const [filter, setFilter] = useState('全部');
  const [selectedReport, setSelectedReport] = useState<any>(null);

  const filters = ['全部', '人形机器人', '动力电池', '半导体', '创新药', '工程机械'];
  
  const filteredData = filter === '全部' 
    ? LIBRARY_DATA 
    : LIBRARY_DATA.filter(item => item.industry === filter);

  const handleCardClick = (report: any) => {
    if (!report.locked) {
      setSelectedReport(report);
    }
  };

  const getReportData = (company: string) => {
    if (company === '宇树科技') return UNITREE_REPORT;
    if (company === '宁德时代') return CATL_REPORT;
    return UNITREE_REPORT; // Fallback
  };

  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="space-y-8">
      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        {filters.map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2 rounded-lg text-sm transition-all duration-300 ${
              filter === f 
                ? 'bg-gradient-to-r from-aria-cyan/20 to-aria-purple/20 border border-aria-cyan/50 text-white shadow-[0_0_15px_rgba(0,217,255,0.2)]' 
                : 'bg-white/5 border border-white/10 text-aria-text-sub hover:bg-white/10'
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredData.map((report) => (
          <AuroraCard 
            key={report.id}
            onClick={() => handleCardClick(report)}
            className={`
              p-6 relative group transition-all duration-300
              ${report.locked 
                ? 'opacity-60 cursor-not-allowed' 
                : 'cursor-pointer hover:-translate-y-1 hover:border-aria-cyan/30'
              }
            `}
          >
            {!report.locked && (
              <div className="absolute top-0 left-0 right-0 h-[3px] bg-gradient-to-r from-aria-cyan to-aria-purple" />
            )}
            
            <div className="flex justify-between items-start mb-4">
              <div>
                <div className="text-xs text-aria-text-sub font-mono mb-1">{report.industry}</div>
                <h3 className="text-xl font-bold text-white group-hover:text-aria-cyan transition-colors">{report.company}</h3>
              </div>
              {report.locked ? (
                <Lock className="w-5 h-5 text-aria-text-sub" />
              ) : (
                <div className="w-8 h-8 rounded-full bg-aria-cyan/10 flex items-center justify-center text-aria-cyan">
                  <FileText className="w-4 h-4" />
                </div>
              )}
            </div>

            <div className={`space-y-4 ${report.locked ? 'blur-[2px]' : ''}`}>
              <div className="flex items-center justify-between text-sm">
                <div className="flex items-center gap-2 text-aria-text-sub">
                  <User className="w-4 h-4" />
                  {report.author}
                </div>
                <div className="flex items-center gap-2 text-aria-text-sub">
                  <Layers className="w-4 h-4" />
                  {report.modules} Modules
                </div>
              </div>
              
              <div className="pt-4 border-t border-white/10 flex justify-between items-center">
                <div className="text-xs text-aria-text-sub">ARIA Score</div>
                <div className="text-2xl font-mono font-bold text-white">{report.score}</div>
              </div>
            </div>

            {report.locked && (
              <div className="absolute inset-0 flex items-center justify-center z-10">
                <div className="px-3 py-1 rounded bg-black/50 backdrop-blur-md border border-white/10 text-xs text-white flex items-center gap-2">
                  <Lock className="w-3 h-3" /> Access Restricted
                </div>
              </div>
            )}
          </AuroraCard>
        ))}
      </div>

      {/* Full Screen Modal */}
      <AnimatePresence>
        {selectedReport && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8"
          >
            <div 
              className="absolute inset-0 bg-[#050810]/85 backdrop-blur-xl"
              onClick={() => setSelectedReport(null)}
            />
            
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="relative w-full max-w-6xl h-[90vh] bg-aria-card border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex"
            >
              {/* Close Button */}
              <button 
                onClick={() => setSelectedReport(null)}
                className="absolute top-4 right-4 z-20 p-2 rounded-full bg-white/5 hover:bg-white/10 text-white transition-colors"
              >
                <X className="w-6 h-6" />
              </button>

              {/* Main Content (85%) */}
              <div className="w-[85%] h-full overflow-y-auto p-12 custom-scrollbar">
                <ReportContent 
                  data={getReportData(selectedReport.company)} 
                  company={selectedReport.company} 
                />
              </div>

              {/* Navigation (15%) */}
              <div className="w-[15%] h-full border-l border-white/10 bg-white/[0.02] p-6">
                <div className="text-xs font-mono text-aria-text-sub mb-4">CONTENTS</div>
                <nav className="space-y-2">
                  {['M0', 'M1', 'M2', 'M3', 'M5', 'M6'].map((id) => (
                    <button
                      key={id}
                      onClick={() => scrollToSection(id.toLowerCase())}
                      className="block w-full text-left text-sm text-aria-text-sub hover:text-aria-cyan hover:bg-white/5 px-3 py-2 rounded transition-colors"
                    >
                      {id} Module
                    </button>
                  ))}
                </nav>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
